### ISSUE TITLE
Replace "Raspberry Pi" texts

### ISSUE THREAD

**Issue by matthieu-lapeyre** [poppy-project/puppet-master#12]
With a Poppy humanoid I have the button "shutdown the raspberry pi".r 

<img width="1431" alt="capture d ecran 2016-04-26 a 21 34 58" src="https://cloud.githubusercontent.com/assets/4503773/14831609/c33ccb36-0bf6-11e6-8470-c7b79cbbe607.png">

 I guess it mays have several others fields with the wrong name in the puppet master interface

**Comment by pierre-rouanet** [comment]
Should be fixed by a34416ee2a9198e12f9086e3ddebadab1ee530f6 and https://github.com/poppy-project/odroid-poppysetup/commit/0cb749f57ab543b2ed065e8b00ad61a108c948ef

Need to rebuild an ISO and test...

**Comment by show0k** [comment]
Tested, it is fixed.
