### ISSUE TITLE
Logs Error 500

### ISSUE THREAD

**Issue by matthieu-lapeyre** [poppy-project/puppet-master#14]
The robot is lagging _(motor no more move after command in the monitor)_, check the log and fall on this error: 

<img width="1014" alt="capture d ecran 2016-04-27 a 21 59 55" src="https://cloud.githubusercontent.com/assets/4503773/14866326/7696491a-0cc3-11e6-8f74-853b200f6d79.png">

**Comment by show0k** [comment]
Can you reproduce this issue ?

**Comment by matthieu-lapeyre** [comment]
Not sure how to reproduce it, it's not the first time it happen.
I think it may be caused by a very high number of timeout error ...

**Comment by show0k** [comment]
Related to #22. I close this one.
