### ISSUE TITLE
test mode on windows

### ISSUE THREAD

**Issue by jjehl** [poppy-project/puppet-master#26]
"You can run it in test mode that can be used on any computer "
On my computer (win7) I need to create manualy puppet-master.log and poppy-config.yaml because the system fail to do it. 
There isn't any setting for wifi configuration ? So how do you manage this ?

**Comment by pierre-rouanet** [comment]
> On my computer (win7) I need to create manualy puppet-master.log and poppy-config.yaml because the system fail to do it. 

To be honest, puppet master is mainly intended to work on raspbian and somehow let me debug on my linux/os x laptop. I don't really have time to add support for windows. So I gladly integrate any PR in this direction but I won't work on this at the moment.

> There isn't any setting for wifi configuration ? So how do you manage this ?
> We don't at the moment. It's planned for the next release.

**Comment by jjehl** [comment]
Maybe I can add contribution to puppet master ( I need some management for wifi on Raspbian). Just a question, is there a reason for not using Django for this app ?

**Comment by pierre-rouanet** [comment]
> Just a question, is there a reason for not using Django for this app ?

A simple one :) We try to use the simplest solution at first. Maybe in the future we will use Django app system for this kind of solution. Do not hesitate to suggest a django app, it will be a good discussion basis!
