### ISSUE TITLE
Strange behaviour of PoppyDeamon

### ISSUE THREAD

**Issue by show0k** [poppy-project/puppet-master#30]
When poppy-services is called with a subprocess.Popen in PoppyDeamon, Flask is blocked until the robot is definitely started or when definitely failed to start.
To reproduce the bug: unplug a motor, click on "restart the robot", go to log and wait.
Any ideas @damiencaselli ?

**Comment by ghost** [comment]
No idea.

**Comment by show0k** [comment]
Flask is not blocked, only the stdout of the `poppy-services` was not flushed, and didn't sync correctly when it was called from a subprocess.
As it works previously without having to flush, I suppose it is something related closely to how Linux manage stdout.
